article: https://developers.hardwario.com/projects/radio-co2-monitor
video: https://youtu.be/jGxjl5v7kqE
images:
  - title:
    url: https://raw.githubusercontent.com/hardwario/website/master/static/kits-images/co2-monitor/main.png
articles:
  - title: Radio CO2 Monitor
    url: https://www.hackster.io/jakub-smejkal/radio-co2-monitor-311d2c
    description: Monitor your workspace or your home with this simple solution that sends all the data by radio so you can work with them.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050366/_TtbY6sZnSM.blob?auto=compress%2Cformat&w=900&h=675&fit=min
assembly:
  - name: HARDWARIO CO2 Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Battery Module
  - name: HARDWARIO Temperature Tag
    optional: true
  - name: HARDWARIO Humidity Tag
    optional: true
  - name: HARDWARIO Barometer Tag
    optional: true
